# Main build settings
[build]
  # Tells Netlify where to find the serverless functions
  functions = "netlify/functions"

# Global settings for all functions
[functions]
  # Use the modern and fast 'esbuild' bundler
  node_bundler = "esbuild"

# Increase the timeout for functions that can be slow due to external API calls.
# Timeout is extended to 25 seconds, which is compatible with the free plan.

[functions.scrape]
  timeout = 25

[functions.affinity-search]
  timeout = 25

[functions.ask-gemini]
  timeout = 25

[functions.triage-links]
  timeout = 25

# NEW FUNCTIONS
[functions.fetch-content]
  timeout = 25

[functions.analyze-text]
  timeout = 25